### PR TITLE
Switch to use console.log for logging

### PR DESCRIPTION
**Pull request by limzykenneth**
I know at some point you changed to use DEBUG module for logging but hear me out here. Personally I feel the "DEBUG=onchange" step feels a bit too unnatural, even with build tools, and might seem weird to new users. DEBUG is meant to be a debug module after all. 

By using the "colors" module the same effect with colours can be achieve and the only thing that is lost is the timestamp.

Default is still kept as quiet mode. So instead of "DEBUG=onchange" we can just use minimist parsing that you already used to look for a "-d" flag which will enable noisy mode.

Naturally, it's your call though.  : )

### CODE REVIEW

**Comment by Qard** [comment]
Thanks for the PR, sorry it took so long to get to it. :)

Rather than all those console.log calls wrapped in if statements everywhere, it'd probably be better to just replace the `log` function.

```js
function log () {
  if (noise) console.log.apply(console, arguments)
}
``` 

Also, I'd prefer a name like `verbose` to `noise`.

**Comment by limzykenneth** [comment]
Yeah, I thought that was a bit messy as well.

Maybe for the flag use -v for verbose as well?

**Comment by Qard** [comment]
The presence of `\n` is a bit inconsistent. Can you just remove those?

I'm not sure how I feel about colors. It's pretty, but doesn't translate well to logs or terminals without color support. Also, the color of the `onchange` text seems to be inconsistent.

If you remove the `\n` and colors usage here, I'll merge this and then I can think about colors in another issue.

**Comment by limzykenneth** [comment]
Ok. The colors are added just to mimic the original behaviour using the 'Debug' module, should be fine without them I guess.

**Comment by Qard** [comment]
Merged and released as 2.0.0.

**Pull request merged**
