### PR TITLE
feat: add more replacements

### PR DESCRIPTION
**Pull request by forivall**
What it says on the tin. I use it for stuff like `onchange -a './*.dot' -- dot -T svg '-o{{changedBaseNoExt}}.svg' '{{changed}}`

### CODE REVIEW

**Comment by blakeembrey** [comment]
This sounds like a good idea, what if we provided functions that could be used instead?

**Comment by blakeembrey** [comment]
I think I’d need to update or switch the template library, but it should be doable.

**Comment by forivall** [comment]
yeah, that works for me too. i kinda based it on what's available in [vscode template variables](https://code.visualstudio.com/docs/editor/variables-reference), but shortened the names

**Comment by Qard** [comment]
Functions are probably more complex than it needs to be. This PR satisfies this particular need. If anything else comes up later can always expand it further when a use case arises. 🤷

**Comment by blakeembrey** [comment]
That’s reasonable. My only concern left is the variables are a little confusing to read. I think that may be removed by changing it to “file” instead of “changed”. Ideally the names will be as self documenting as possible. Would you be willing to add a file alias in this PR and we can land it as the next release? I think the short names are OK, but I may be confused as a first time user reading “changedbasenoext”. Maybe just “basenameNoExt” works, but happy to have pushback on this x - I could be over analyzing.

**Comment by blakeembrey** [comment]
@forivall If you'd like, I can take a stab at updating your PR as-is to "file" - we just just have both "changed" and "file" for backward compatibility.

**Comment by forivall** [comment]
k, i finally made the change :P

**Review by Qard — APPROVED** [review]

**Pull request merged**
