### PR TITLE
Enable restarting of running processes

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/Qard/onchange/issues/28, https://github.com/Qard/onchange/issues/25 and https://github.com/Qard/onchange/issues/22.

### CODE REVIEW

**Comment by Qard** [comment]
Nice, thanks! I'll review this tonight. :smile_cat:

**Comment by paked** [comment]
@blakeembrey @Qard Any updates on this?

**Comment by Qard** [comment]
Sorry, forgot about this...I haven't really used onchange for anything lately, so it's not exactly at the top of my mind.

@blakeembrey Want commit/publish access. I'm not really doing a great job of maintaining this myself.

**Comment by blakeembrey** [comment]
@Qard Sure, I can help provide updates and issue maintenance :+1:

**Comment by Qard** [comment]
I gave you push access to this repo and publish access on npm. Thanks for the help! :smile_cat:

**Comment by blakeembrey** [comment]
Thanks, I'll merge what's here and do a release. If I come back around, we can see if there's a chance of getting tests in too :smile:

**Pull request merged**
