### PR TITLE
Update all deps

### PR DESCRIPTION
**Pull request by vinyfc93**
Just keeping things up to date.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@vinyfc93 This isn't necessary, the purpose of `^` means the latest version in the major range is installed automatically.

**Comment by vinyfc93** [comment]
@blakeembrey, but one of the dependencies, 'cross-spawn' is out of range.

**Comment by blakeembrey** [comment]
I'm aware, there's also a PR for it. But it's a breaking change for this module.

**Comment by blakeembrey** [comment]
See https://github.com/Qard/onchange/pull/92 and https://github.com/moxystudio/node-cross-spawn/blob/master/CHANGELOG.md#700-2019-09-03.

**Pull request closed without merging**
